version: '3.6'

services:

  sae:
    image: sae:dev
    network_mode: bridge
    build: .
    volumes:
      - node_modules_cache:/usr/app/node_modules
      - ./src:/usr/app/src
      - ./public:/usr/app/public
      - ./next.config.js:/usr/app/next.config.js
      - ./.babelrc:/usr/app/.babelrc
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
    ports:
      - 3000:3000
      
volumes:
  node_modules_cache: {}